### ISSUE TITLE
ink gun doesn't work on 3ds

### ISSUE THREAD

**Issue by KaatRootje18** [SplatooD/splatood#2]
When emulating the .nes rom on the 3ds you can use the ink roller, but not the ink gun. I tried all buttons on my 3ds, but none of them worked...

**Comment by Sur3** [comment]
The gun (charger) is a bit special, it uses the same button you use to splat with the roller, but you have to keep the button pressed until it fires. That confused me as well at first and I think the weapons need some more balancing; I've some ideas on different weapons as well.

PS:
Cool, didn't know you can play nes roms on 3ds.

**Comment by KaatRootje18** [comment]
Splatting with the ink roller doesn't work as well. But I think it is my 3ds then (I dont know why because all the nes games on 3ds run just fine). And yeah, it is cool. There even is a n64 emulator for 3ds in the making

**Comment by Sur3** [comment]
Splatting with the roller also doesn't work? Does the squid mode work? I could provide a .nes file with swapped squid-mode (B) and splat (A) button then to see if it's the button or some deeper problem..

**Comment by KaatRootje18** [comment]
Splating doesn't work, squid mode does work. If you can swap those than it would be nice to test. :)

**Comment by Sur3** [comment]
Ok here is a version with swapped buttons:
http://homepages.uni-paderborn.de/neuron/splatood/splatood-swapped.nes

**Comment by KaatRootje18** [comment]
Thanks man, really nice. Can i add you on discord?

**Comment by Sur3** [comment]
yeah it's: kurktu#3416

**Comment by KaatRootje18** [comment]
Cool, Ive send you a friend request. That is easier chatting

**Comment by Sur3** [comment]
Ok seems to work after all, please close the bug report.
